### ISSUE TITLE
License must be GPLv3, not CC0-1.0

### ISSUE THREAD

**Issue by ryonakano** [teamcons/eOSdock-themeswitcher#3]
As [README says](https://github.com/teamcons/eOSdock-themeswitcher/blob/4afa3e09edf6d35cc3c3fffed9625a2311a91298/README.md?plain=1#L36-L37), this project contains code taken from [Dock](https://github.com/elementary/dock), which is licensed under GPLv3. So, this project must be also licensed under GPLv3, not CC0-1.0, because of copyleft.

**Comment by teamcons** [comment]
Understood. My apologies - Ive been meaning to change it
I will also link back to Dock in the Readme when i have a minute.
